polling_booth/urls.py
from django.urls import path
from . import views

app_name = "polling_booth"
urlpatterns = [path('',views.IndexView.as_view(),name="index"),
    path('<int:pk>/',views.DetailView.as_view(),name="detail"),
    path('<int:pk>/result',views.ResultView.as_view(),name="result"),
    path('<int:pk>/vote',views.vote,name="vote")
]

polling_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polling_booth.urls')),
]

polling_booth/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Question(models.Model):
    ques_text = models.CharField(max_length=200)
    publish_date = models.DateField('date published')

    #used for the object representation
    def __str__(self):
        return self.ques_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.publish_date <= now

class Choice(models.Model):
    # to define the relationship, ForeignKey are used
    ques = models.ForeignKey(Question,on_delete=models.CASCADE) #arguments- to class which is relatied,
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polling_booth/views.py
from django.shortcuts import render,get_object_or_404
from django.http import Http404,HttpResponse,HttpResponseRedirect
from .models import Question,Choice
from django.db.models import F
from django.utils import timezone
from django.urls import reverse
from django.views import generic
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polling_booth/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(publish_date__lte=timezone.now()).order_by('-publish_date')[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polling_booth/detail.html'
    def get_queryset(self):
        return Question.objects.filter(publish_date__lte=timezone.now())

class ResultView(generic.DetailView):
    model = Question
    template_name = 'polling_booth/result.html'

def vote(request,pk):
    question = get_object_or_404(Question,pk=pk)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'polling_booth/detail.html',context={'question':question,'error_message':
        "You didn't select any choice"})
    else:
        selected_choice.votes= F('votes') +1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polling_booth:result', args=(question.id,)))

polling_booth/templates/polling_booth/detail.html
<h1>{{ question.ques_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polling_booth:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>o

polling_booth/templates/polling_booth/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polling_booth:detail' question.id %}">{{ question.ques_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polling_booth/templates/polling_booth/result.html
<h1>{{ question.ques_text }}</h1>
<p>You are at the Result Page<p>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polling_booth:detail' question.id %}">Vote again?</a>